
name: deploy-auth 

on: 
  push: 
    branches: 
      - master 
    paths: 
      - 'auth/**'

jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t alisher83/auth . 
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env: 
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push alisher83/auth
      - uses: digitalocean/action-doctlt@v2
        with: 
          token: 
            token: ${{ secrets.DO_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save k8s-1-21-5-do-0-nyc1-1635545928792
      - run: kubectl rollout restart deployment auth-depl 
